update cavan-init
Signed-off-by: Fuang.Cao <cavan.cfa@gmail.com>

diff --git a/script/cavan-init b/script/cavan-init
--- a/script/cavan-init
+++ b/script/cavan-init
@@ -309,8 +309,8 @@ function config_aptget()
 
 	mkdir -pv "${DIR_SOURCES_LIST}" || return 1
 	echo "deb http://download.virtualbox.org/virtualbox/debian ${DISTRIB_CODENAME} contrib" > "${DIR_SOURCES_LIST}/virtualbox.list"
-	echo "deb http://archive.ubuntukylin.com:10006/ubuntukylin trusty main" > "${DIR_SOURCES_LIST}/sogoupinyin.list"
-	echo "deb http://ftp.de.debian.org/debian wheezy main" > "${DIR_SOURCES_LIST}/debian.list"
+	# echo "deb http://archive.ubuntukylin.com:10006/ubuntukylin trusty main" > "${DIR_SOURCES_LIST}/sogoupinyin.list"
+	# echo "deb http://ftp.de.debian.org/debian wheezy main" > "${DIR_SOURCES_LIST}/debian.list"
 
 	wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -
 }
@@ -360,7 +360,28 @@ function install_applications()
 	apt-get clean || return 1
 	dpkg --configure -a || return 1
 	apt-get update --fix-missing # || return 1
-	apt-get install -fy --force-yes --show-progress $(cat "${FILE_APP_CONFIG}" | sed 's/#.*$//g') || return 1
+	apt-get install -fy --force-yes --show-progress $(cat "${FILE_APP_CONFIG}" | sed 's/#.*$//g') ||
+	{
+		rm -rf "${FILE_APP_FEILED}" || return 1
+
+		cat "${FILE_APP_CONFIG}" | while read line
+		do
+			[[ $line = \#* ]] && continue
+
+			echo "Install application: $line"
+			apt-get install -fy --force-yes $line && continue
+
+			echo "$line" >> "${FILE_APP_FEILED}"
+		done
+
+		[ -f "${FILE_APP_FEILED}" ] &&
+		{
+			echo "Failed to install application:"
+			cat "${FILE_APP_FEILED}"
+			return 1
+		}
+	}
+
 	apt-get autoremove -fy --force-yes --show-progress || return 1
 }
 
